### ISSUE TITLE
ConcurrentModificationException when we traverse registeredTasks

### ISSUE THREAD

**Issue by oliverhu** [tony-framework/TonY#664]
We observed this failure when run 700+ workers

```
java.util.ConcurrentModificationException: null
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1558) ~[?:1.8.0_172]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_172]
	at com.linkedin.tony.ApplicationMaster.startupFailed(ApplicationMaster.java:1282) ~[tony-core-0.4.9.jar:?]
	at com.linkedin.tony.ApplicationMaster.monitor(ApplicationMaster.java:685) ~[tony-core-0.4.9.jar:?]
	at com.linkedin.tony.ApplicationMaster.run(ApplicationMaster.java:402) ~[tony-core-0.4.9.jar:?]
	at com.linkedin.tony.ApplicationMaster.main(ApplicationMaster.java:334) [tony-core-0.4.9.jar:?]
```
`registeredTasks` is updated in a separate thread and can be updated whie we traverse it. We need to make sure `registeredTasks` can be safely passed to .stream().forEach().

**Comment by zuston** [comment]
https://github.com/tony-framework/TonY/pull/665 solved.
