### ISSUE TITLE
ERROR ApplicationMaster:496 - Exception while preparing AM org.apache.hadoop.yarn.exceptions.YarnException: Can't resolve the ip of ubuntu 	at com.linkedin.tony.util.Utils.getHostNameOrIpFromTokenConf(Utils.java:365) 	at com.linkedin.tony.ApplicationMaster.prepare(ApplicationMaster.java:476) 	at com.linkedin.tony.ApplicationMaster.run(ApplicationMaster.java:368) 	at com.linkedin.tony.ApplicationMaster.main(ApplicationMaster.java:342)

### ISSUE THREAD

**Issue by ckqqqq** [tony-framework/TonY#673]
Hello,  I have a new problem running the pytorch program in a pseudo-distributed Hadoop environment. The management page of yarn reports this error.
The error is reported as follows.
2022-05-26 13:55:00 WARN  NativeCodeLoader:60 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2022-05-26 13:55:01 INFO  ApplicationMaster:448 - Preparing application master..
2022-05-26 13:55:01 INFO  NMClientAsyncImpl:138 - Upper bound of the thread pool size is 500
2022-05-26 13:55:01 INFO  DefaultNoHARMFailoverProxyProvider:64 - Connecting to ResourceManager at localhost/127.0.0.1:8030
2022-05-26 13:55:01 ERROR ApplicationMaster:496 - Exception while preparing AM
org.apache.hadoop.yarn.exceptions.YarnException: Can't resolve the ip of ubuntu
	at com.linkedin.tony.util.Utils.getHostNameOrIpFromTokenConf(Utils.java:365)
	at com.linkedin.tony.ApplicationMaster.prepare(ApplicationMaster.java:476)
	at com.linkedin.tony.ApplicationMaster.run(ApplicationMaster.java:368)
	at com.linkedin.tony.ApplicationMaster.main(ApplicationMaster.java:342)
2022-05-26 13:55:01 INFO  ApplicationMaster:347 - Application Master failed. Exiting

My environment:
Ubuntu20.04
openjdk 1.8
Hadoop3.3.3

**Comment by zuston** [comment]
It looks like you set the nm host is `ubuntu`? But it can't be resolved to ip.

**Comment by ckqqqq** [comment]
I can access the management page of yarn when typing ubuntu:8042 into my browser.
